# -*- coding: utf-8 -*-
"""명사추출(한나눔).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yYraKNF_cU-uCbSkfX2UFDaLpxq4HeSV
"""


from konlpy.tag import Hannanum
import pandas as pd
import numpy as np
import glob
import os


#print(pd.__version__)  1.5.3
#print(np.__version__)  1.23.5

import preprocessing
df=preprocessing.prepro()

hannanum=Hannanum()

df['hannanum_nouns']=''
for idx,row in df.iterrows():
    temp=hannanum.nouns(row['text'])
    temp_list=[word for word in temp if len(word)>0]
    df.at[idx,'hannanum_nouns']=','.join(temp_list)


# csv 파일 생성 및 저장
script_dir = os.path.dirname(__file__)
new_relative_path = "../../data/processed/Hannanum_dataset.csv"
new_file_path = os.path.join(script_dir, new_relative_path)

df.to_csv(new_file_path,encoding='utf-8', index=False)