# -*- coding: utf-8 -*-
"""(okt+hannanum)+keybert_extract_keywords.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ERy9JI6riakIngjW_2qGLe9Z2mTL67eQ
"""

#!pip install keybert        #0.8.3

from keybert import KeyBERT
import pandas as pd         #1.5.3
import os

temp={'okt':[],'hannanum':[]}
df=pd.DataFrame(temp)

script_dir = os.path.dirname(__file__)
relative_path1 = "../../data/raw/test_10_data.csv"
file_path1 = os.path.join(script_dir, relative_path1)

df_okt=pd.read_csv(file_path1,encoding='euc-kr')

del_col=['Unnamed: 0','번호','요약문']
df_okt=df_okt.drop(del_col,axis=1)

model = KeyBERT()
for idx,row in df_okt.iterrows():
    n = len(row['중요단어'].split(','))
    keyword=model.extract_keywords(row['추출단어'],top_n=n)
    df.at[idx,'okt']=','.join([word for word,_ in keyword])
    if idx==10:
        break

relative_path2 = "../../data/processed/Okt_dataset.csv"        #한나눔 폴더로 경로 변경해야됨
file_path2 = os.path.join(script_dir, relative_path2)
df_hannanum=pd.read_csv(file_path2,encoding='euc-kr')

df_hannanum=df_hannanum.drop(del_col,axis=1)

for idx,row in df_hannanum.iterrows():
    n = len(row['중요단어'].split(','))
    keyword=model.extract_keywords(row['추출단어'],top_n=n)
    df.at[idx,'hannanum']=','.join([word for word,_ in keyword])
    if idx==10:
        break

print(df['okt'])
print(df['hannanum'])

df['중요단어']=df_okt['중요단어']

okt_score=0
hannanum_score=0
for idx,row in df.iterrows():
    main_words=row['중요단어'].split(',')

    okt_words=row['okt'].split(',')
    hannanum_words=row['hannanum'].split(',')

    okt_score+=len(set(main_words)&set(okt_words))/len(main_words)
    hannanum_score+=len(set(main_words)&set(hannanum_words))/len(main_words)
    if idx==10:
        break
okt_score=okt_score/len(df)*100
hannanum_score=hannanum_score/len(df)*100

print(f'okt 정확도 : {okt_score}')
print(f'hannanum 정확도 : {hannanum_score}')